version: "3.7"
services:
  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 8088:8080
    # command: ['yarn', 'install']
    command: ['yarn', 'serve']  
    networks:
      - ninostore

networks:
  ninostore:
    name: network_laravel_net
    driver: bridge